#!/bin/bash

PASSWORD_FILE=/x11vnc-passwords
cat <<EOF > $PASSWORD_FILE
# This file is generated by entry.sh. Do not edit.
poltergeist
$ACCESS_PASSWORD
__BEGIN_VIEWONLY__
bearwitness
$VIEW_PASSWORD
EOF

if [ -z $DISABLE_PASSWORDS ]; then
    echo "Enabling password protection"
    PASSWORD_OPT="-passwdfile $PASSWORD_FILE"
else
    echo "Disabling password protection"
    PASSWORD_OPT=
fi

echo "\n#"
echo "# Starting x11vnc"
echo "#"

x11vnc \
  -display $DISPLAY \
  -listen localhost \
  -noshm \
  -no6 \
  -rfbport $VNC_PORT \
  -nopw \
  -shared \
  -alwaysshared \
  -bg \
  -forever \
  -quiet \
  $PASSWORD_OPT

echo "\n#"
echo "# Starting novnc"
echo "#\n"

exec websockify --web /usr/share/novnc $WEB_PORT localhost:$VNC_PORT
